---
language: python
python: "2.7"
sudo: required
services:
  - docker

before_install:
  - docker --version
install:
  - pip install molecule==2.5.0
  - pip install -U ansible==2.4.2.0
  - pip install -U testinfra==1.7.1
  - pip install docker-py
script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
