---
- name: Set templatized Kapacitor configuration
  template:
    src: kapacitor.conf.j2
    dest: "/etc/kapacitor/kapacitor.conf"
    force: "yes"
    backup: "yes"
    owner: kapacitor
    group: kapacitor
    mode: 0744
  notify: restart kapacitord
  when: kapacitor_template_configuration

- name: Verifying kapacitord is started and enabled
  service:
    name: kapacitor
    state: started
    enabled: yes

- debug: msg="Variables kapacitor_tasks_to_enable, kapacitor_stream_thresholds, kapacitor_stream_thresholds_disable has been deprecated and will be removed in a future release. Use kapacitor_tasks."
  when: (kapacitor_tasks_to_enable is defined and kapacitor_tasks_to_enable) or (kapacitor_stream_thresholds is defined and kapacitor_stream_thresholds) or (kapacitor_stream_thresholds_disable is defined and kapacitor_stream_thresholds_disable)
  failed_when: true
  ignore_errors: true

- include_tasks: configure-ticks.yml
  when: kapacitor_tasks_to_enable is defined
  tags: [kapacitor, ticks]

- include_tasks: configure-thresholds.yml
  when: kapacitor_stream_thresholds is defined
  tags: [kapacitor, thresholds]

- include: configure-tasks.yml
  when: kapacitor_tasks is defined
  tags: [kapacitor, tasks]
